version: '3.5'

services:
  production:
    image: production-version-1.0.0
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "8081:8080"
    env_file:
      - .env
    volumes:
      - ./src:/usr/src/app/src