version: '3.8'

services:
  development-be:
    image: development-version-1.0.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./src:/usr/src/app/src
